config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :accounts do
    collection do
      get  'check_email'
      get  'email_check'
      get  'forget_password'
      get  'password_reset'
      get  'logo'
      get  'icon'
      get  'default_dp'
      post 'password_change'
    end
  end

  resources :users do
    collection  do
      get  'image_display'
      post 'follow'
      post 'unfollow'
    end
  end

  resources :admins do
    collection do
      post 'default'
    end
  end

  resources :songs do
    collection do
      get 'like'
      get 'unlike'
      get 'song'
      get 'test'
      get 'select_fillter'
    end
  end

  resources :comments

  resources :conversations do
    collection do
      get 'get_message'
    end
    resources :messages
  end

  root to: 'songs#index'

  mount ActionCable.server => '/message'

  match '/signout' ,         to: 'accounts#signout',              via: [:delete]
  match '/login' ,           to: 'accounts#login',                via: [:post]
  match '/signin' ,          to: 'accounts#signin',               via: [:get]
  match '/signup',           to: 'accounts#new',                  via: [:get]


end

app/models/user.rb
class User < ApplicationRecord
  has_one :authentication, dependent: :destroy
  has_many :songs,dependent: :destroy
  has_many :comments,dependent: :destroy
  has_many :followeds, foreign_key: "follower_id",class_name: "FollowerDetail",dependent: :destroy
  has_many :followers, foreign_key: "followed_id",class_name: "FollowerDetail",dependent: :destroy
  has_many :conversations_send, foreign_key: "sender_id",class_name: "Conversation",dependent: :destroy
  has_many :conversations, foreign_key: "receiver_id", dependent: :destroy

  validates :name,presence: true
  validates :email,presence: true

  before_save :change_number_format

  def following?(other_user)
    followeds.find_by_followed_id(other_user.id)
  end

  def follow!(other_user)
    followeds.create!(followed_id: other_user.id)
  end 

  def unfollow!(other_user)
    followeds.find_by_followed_id(other_user.id).destroy
  end

#  def online?
#    !Redis.new.get("user_#{self.id}_online").nil?
#  end

  private
  def change_number_format
    phone = phone.to_i
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user, only: [:index,:edit,:update,:destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @follow_unfollow = FollowerDetail.new
    @songs = Song.user_filter(@user.id).paginate(page: params[:page], per_page: 2)
    respond_to do |format|
        format.html
        format.js
    end
  end

  def image_display
    user = User.find(params[:id])
    send_data(user.pic,:type=>user.pictype, :disposition => 'inline' )
  end
  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    if params[:user][:image].present?
       params[:user][:pictype]  = params[:user][:image].content_type.chomp
       params[:user][:pic]      = params[:user][:image].read
       params[:user][:dpic]     = nil
    else
       params[:user][:dpic]     = "/assets/profile.png"
    end
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        params[:user][:user_id] = @user.id
        @authe = Authentication.new(authsignup_params)
        if @authe.save
          sign_in @authe
          UserMailer.welcome_email(@user).deliver_later
          format.html { redirect_to @user,:flash => {:success =>'welcome Profile was successfully created.' }}
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    if params[:user][:image].present?
       params[:user][:pictype]  = params[:user][:image].content_type.chomp
       params[:user][:pic]      = params[:user][:image].read
       params[:user][:dpic]     = nil
    else
       params[:user][:dpic]     = "/assets/profile.png"
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user,:flash => {:success => "#{@user.name} was successfully updated." }}
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, :flash => {:success =>'Profile was successfully destroyed.' }}
      format.json { head :no_content }
    end
  end

  def follow
     @user = User.find(params[:follow][:followed_id])
     current_user.follow!(@user)
     respond_to do |format|
       format.html {}
       format.js {}
     end
  end
 
  def unfollow
     @user = User.find(params[:follow][:followed_id])
     current_user.unfollow!(@user)
     respond_to do |format|
       format.html {}
       format.js {}
     end
  end

  def followers
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  def following
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:name,:phone,:gender,:city,:country,:pic,:pictype,:dpic,:aboutme)
    end

    def authsignup_params
      params.require(:user).permit(:email,:password,:user_id)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def sign_in(authenti)
    cookies.permanent[:remember_token]=authenti.remember_token
    self.current_user= authenti
  end

  def current_user=(user)
    @current_user=current_user
  end

  def current_user
    user=Authentication.find_by_remember_token(cookies[:remember_token])
    if(!user.nil?)
      @current_user ||= User.find(user.user_id)
    end
  end

  def current_user?(user)
    user==current_user
  end

  def signedin?
    !current_user.nil?
  end

  def sign_out
    self.current_user=nil
    cookies.delete(:remember_token)
  end

  def signed_in_user
    unless signedin?
      redirect_to signin_path
    end
  end

  def user_image(user_id)
    user = User.find(user_id)
    if user.dpic.nil?
      url_for( :action => "image_display",:id => user.id, :controller=> "users" )
    else
      url_for( :action => "default_dp", :controller=> "accounts" )
    end
  end

  def admin
    unless current_user.authentication.is_admin?
      redirect_to signin_path
    end
  end
end

app/views/users/_follow.html.erb
<div id="follow_button">
  <%=form_for(:follow,url: follow_users_path,remote:true) do |f| %>
    <%= f.hidden_field :followed_id, value: @user.id %>
    <%= f.submit "Follow", id: "Follow_button", class: "btn btn-outline-primary" %>
  <% end %>
</div>
 

app/views/users/_followers.html.erb
<div class="col-12 small_padding">
<h3 class="text-center"><%= @user.followers.count %>  Followers </h3>
<% if @user.followers.any? %>
   <ul class="list-group list-group-flush">

   <% @user.followers.each do |user| %>
     <li class="list-group-item col-md-12">
       <div class="row">
         <div class="col-3"><img class="rounded-circle img-fluid" height="50" style ="width: 100%" src="<%= user_image(user.follower.id)%>" /></div>
         <div class="col-7">
           <div class="row">
             <div class="col-8"><%= link_to user.follower.name, user_path(user.follower.id) %></div>
             <% if current_user.id != user.follower.id %><div class="col-4"><span id="follow_unfollow_button"><% if current_user.following?(user.follower) %><%= render 'unfollow' %><% else %><%= render 'follow' %><% end %></span></div><% end %>
           </div>

          <div class="row"> <div class="col-12"><%= user.follower.songs.count %>&nbsp;Songs</div></div>
          </div>
       </div>
     </li>
   <% end %>
 </ul>
 <% elsif !signedin? || @user.id != current_user.id %>
   <p class="text-center border_top mt-2"> No Followers </p>
<% else %>
  <h6 class="text-center border_top mt-2">Upload more songs to win hearts </h6>
<% end %>
</div>

app/views/users/_following.html.erb
<div class="col-12 small_padding">
  <h3 class="text-center"><%= @user.followeds.count %> Following </h3>
<% if @user.followeds.any? %>
   <ul class="list-group list-group-flush">
   <% @user.followeds.each do |user| %>
     <li class="list-group-item col-md-12">
       <div class="row">
         <div class="col-3"><img class="rounded-circle img-fluid" height="50" style ="width: 100%" src="<%= user_image(user.followed.id)%>" /></div>
         <div class="col-7">
           <div class="row">
             <div class="col-8"><%= link_to user.followed.name, user_path(user.followed.id) %></div>
             <% if current_user.id != user.followed.id %><div class="col-4"><span id="follow_unfollow_button"><% if current_user.following?(user.followed) %><%= render 'unfollow' %><% else %><%= render 'follow' %><% end %> </span></div><% end %>
           </div>
           <div class="row"><div class="col-12"> <%= user.followed.songs.count %>&nbsp;Songs</div></div>
         </div>
       </div>
     </li>
   <% end %>
 </ul>
 <% elsif !signedin? || @user.id != current_user.id %>
   <p class="text-center border_top mt-3"> Not following </p>
<% else %>
  <p class="text-center border_top mt-2">Follow Someone for Awesome songs </p>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= form_for(user,role:"form",:multipart => 'true') do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row justify-content-md-center mt-5">
    <div class="col-5 all_border">
          <div class="form-group ">
              <%= f.label :name,class: "control-label" %>
              <%= f.text_field :name,class: "form-control",placeholder: "Name:",:required => true  %>
          </div>

          <div class="form-group">
              <%= f.label :email,class: "control-label" %>
              <%= f.email_field :email,class: "form-control",placeholder: "Email:",:required => true ,id: "check_email" %>
          </div>

          <div class="form-group">
              <%= f.label :phone,class: "control-label" %>
              <%= f.text_field :phone,class: "form-control",placeholder: "Phone",:required =>true, pattern: "\\d*" %>
          </div>

        <div class="form-group">
          <label for="gender_choose" class="control-label"> Gender : &nbsp;</label>
          <select name="user[gender]" class="custom-select" id="gender_choose">
            <option selected> Choose..</option>
            <option value="King" <% if user.gender == "King" %> selected <% end %>>King</option>
            <option value="Queen"<% if user.gender == "Queen" %> selected <% end %>>Queen </option>
          </select>
        </div>

        <div class="form-group">
          <%= f.label :city,class: "control-label" %>
          <%= f.text_field :city,class: "form-control",placeholder: "City",:required => true %>
        </div>

        <div class="form-group">
          <%= f.label :country,class: "control-label" %>
          <%= f.text_field :country,class: "form-control",placeholder: "Country",:required=>true %>
        </div>

        <div class="form-group">
            <%= f.label :Few_lines_about_me,class: "control-label" %>
            <%= f.text_area :aboutme,class: "form-control",placeholder: "About me",:required=>true %>
        </div>


        <div class="row">
          <%= f.submit "Change",class: "btn btn-primary col-md-3 offset-md-5", id:"signup_form"%>
        </div>

      </div>
  </div>
<% end %>

app/views/users/_songshow.html.erb
<% if @songs.any? %>
   <% @songs.each do |song| %>
    <div class="col-12 mb-3" >
     <%= render partial: 'songs/song', locals: {song: song} %>
   </div>
   <% end %>
<% elsif @user.id != current_user.id %>
     <h3 class="text-center"> No Songs uploaded yet. </h3>
<% else %>
   <h3 class="text-center"> World is waiting!! <%= link_to "Upload",new_song_path,class:"btn btn-outline-primary" %> </h3>
<% end %>

app/views/users/_unfollow.html.erb
<div id="unfollow_button">
  <%=form_for(:follow,url: unfollow_users_path,remote:true) do |f| %>
    <%= f.hidden_field :followed_id, value: @user.id %>
    <%= f.submit "Unfollow", id: "unfollow_button", class: "btn btn-outline-primary" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<% flash.each do |key,msg| %>
 <div class="text-center alert alert-<%= key %>"><%= msg %></div>
<% end %>


<h1>Users</h1>
<div id="user_data"></div>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>

      <tr>
        <td> <%= user.name %> </td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<% flash.each do |key,msg| %>
 <div class="text-center alert alert-<%= key %>"><%= msg %></div>
<% end %>

<div class="container" id="profile_song_show">
  <div class="row">
    <div class = "col-12 mt-5 small_padding all_shadow">
      <div class="row">
        <div class="col-2">
          <img class="rounded-circle img-fluid" height="60" style="width: 100%" src="<%= user_image(@user.id) %>">
        </div>
        <div class="col-8 border_left text-center">
          <div class="row">
            <h3 class="col-4"><%= @user.name %></h3>
            <p class="col-7"><%= @user.aboutme %></p>
          </div>
        </div>
        <div class="col-2 border_left">
          <% if signedin? %>
              <div class="row justify-content-center"><% unless current_user?(@user) %> <span id="follow_unfollow_button"><% if current_user.following?(@user) %><%= render 'unfollow' %><% else %><%= render 'follow' %><% end %> <% end %></span></div>
              <div class="row justify-content-center"><% if signedin? && current_user.id == @user.id %><%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-outline-primary' %><% end %></div>
              <div class="row justify-content-center mt-3"><% if signedin? && current_user.id != @user.id %><%= link_to 'Send Message', edit_user_path(@user), class: 'btn btn-outline-primary' %><% end %></div>
              <div class="row justify-content-center mt-1"><% if signedin? && current_user.id == @user.id %><%= link_to 'Change Password',password_reset_accounts_path , class: 'btn btn-outline-primary' %><% end %></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-4">
      <div id="my_songs">
        <p class="row justify-content-center"> <span class="badge badge-default badge-pill"><%= @user.songs.count %> Songs</span></p>
        <%= render partial: 'songshow' %>
      </div>
      <% if @songs.any? %>
         <div id="infinite-scrolling">
           <%= will_paginate @songs %>
         </div>
      <% end %>
    </div>
    <div class="col-4">
      <%= render partial: 'following' %>
    </div>
    <div class="col-4">
      <%= render partial: 'followers' %>
    </div>

</div>

app/views/users/show.js.erb
$('#my_songs').append("<%= j render partial:'songshow' %>");
<% if @songs.next_page %>
$('#infinite-scrolling').replaceWith('<%= j will_paginate @songs %>');
<% else %>
$('.pagination').remove();
<% end %>