config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :accounts do
    collection do
      get  'check_email'
      get  'email_check'
      get  'forget_password'
      get  'password_reset'
      get  'logo'
      get  'icon'
      get  'default_dp'
      post 'password_change'
    end
  end

  resources :users do
    collection  do
      get  'image_display'
      post 'follow'
      post 'unfollow'
    end
  end

  resources :admins do
    collection do
      post 'default'
    end
  end

  resources :songs do
    collection do
      get 'like'
      get 'unlike'
      get 'song'
      get 'test'
      get 'select_fillter'
    end
  end

  resources :comments

  resources :conversations do
    collection do
      get 'get_message'
    end
    resources :messages
  end

  root to: 'songs#index'

  mount ActionCable.server => '/message'

  match '/signout' ,         to: 'accounts#signout',              via: [:delete]
  match '/login' ,           to: 'accounts#login',                via: [:post]
  match '/signin' ,          to: 'accounts#signin',               via: [:get]
  match '/signup',           to: 'accounts#new',                  via: [:get]


end

app/views/layouts/accounts.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Singersarena</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag icon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Singersarena</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= favicon_link_tag icon %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded bottom_shadow" >
       <div class="row">
           <div class="col-2">
              <img class="rounded-circle img-fluid" height="60" style="width: 100%" src="<%= icon %>">
           </div>
           <%= link_to "Singersarena", root_path,class: "navbar-brand col-8" %>
           <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
           </button>
        </div>

           <div class="collapse justify-content-end navbar-collapse" id="navbarNav">
           <ul class="navbar-nav">
             <% if signedin? %>
                <% if current_user.authentication.is_admin? %>
                   <li class="nav-item">
                       <%= link_to "Admin", admins_path,class: "nav-link" %>
                   </li>
                <% end %>
                 <li class="nav-item">
                    <%= link_to "Upload", new_song_path,class: "nav-link" %>
                 </li>
                  <li class="nav-item">
                    <%= link_to current_user.name , current_user, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                     <%= link_to "Message", conversations_path, class: "nav-link" %>
                  </li>
                  <li class="nav-item">
                     <%= link_to "Signout", signout_path, method: "delete", class: "nav-link" %>
                  </li>
              <% else %>
                  <li class="nav-item"><%= link_to "Sign up",signup_path,class: "nav-link btn btn-outline-primary" %></li>&nbsp;
                  <li class="nav-item"><%= link_to "Sign in",signin_path,class: "nav-link btn btn-outline-primary" %></li>
              <% end %>
           </ul>
           </div>
    </nav>

    <%= yield %>
  </body>
</html>