config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :accounts do
    collection do
      get  'check_email'
      get  'email_check'
      get  'forget_password'
      get  'password_reset'
      get  'logo'
      get  'icon'
      get  'default_dp'
      post 'password_change'
    end
  end

  resources :users do
    collection  do
      get  'image_display'
      post 'follow'
      post 'unfollow'
    end
  end

  resources :admins do
    collection do
      post 'default'
    end
  end

  resources :songs do
    collection do
      get 'like'
      get 'unlike'
      get 'song'
      get 'test'
      get 'select_fillter'
    end
  end

  resources :comments

  resources :conversations do
    collection do
      get 'get_message'
    end
    resources :messages
  end

  root to: 'songs#index'

  mount ActionCable.server => '/message'

  match '/signout' ,         to: 'accounts#signout',              via: [:delete]
  match '/login' ,           to: 'accounts#login',                via: [:post]
  match '/signin' ,          to: 'accounts#signin',               via: [:get]
  match '/signup',           to: 'accounts#new',                  via: [:get]


end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :check_key, only: [:password_reset]

  def new
    @user = User.new
  end

  def create
    if params[:user][:image].present?
       params[:user][:pictype]  = params[:user][:image].content_type.chomp
       params[:user][:pic]      = params[:user][:image].read
       params[:user][:dpic]     = nil
    else
       params[:user][:dpic]     = "/assets/profile.png"
    end
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        params[:user][:user_id] = @user.id
        @authe = Authentication.new(authsignup_params)
        if @authe.save
          sign_in @authe
          UserMailer.welcome_email(@user).deliver_later
          format.html { redirect_to @user, :flash => {:success =>'Profile was successfully created.' }}
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end


  def signin
  end

  def login
    user = Authentication.find_by_email(params[:login][:email])
    if user && user.authenticate(params[:login][:password])
      sign_in user
      redirect_to root_path
    else
      respond_to do |format|
        format.html { redirect_to signin_path, :flash => {:danger =>'Password Wrong try again..' }}
        format.json { }
      end
    end
  end

  def forget_password
    if params[:profile].present?
        @authe = Authentication.find_by_email(params[:profile][:email])
        params[:profile][:forgetkey]= SecureRandom.urlsafe_base64
        if @authe.update(authen_params)
          UserMailer.password_reset(@authe).deliver_now
          render :json => '{"key":"success","msg":"Link has been mailed.please check your Mail."}'
        else
          render :json => '{"key":"danger","msg":"Something went wrong try again!!!."}'
        end
    end
  end

  def password_reset

  end

  def password_change
    respond_to do |format|
      if params[:profile][:password] == params[:profile][:again_password]
        if params[:profile][:f_key].present?
            if @user = Authentication.find_by_forgetkey(params[:profile][:f_key])
               @user.update(password_reset_params)
                UserMailer.password_reset_success(@user).deliver_now
                  format.html { redirect_to signin_url,:flash => {:success => 'password successfully Reseted login now.' }}
                  format.json { }
            else
              format.html { redirect_to forget_password_accounts_path,:flash => {:danger => 'Something went wrong please try again.' }}
              format.json { }
            end
        else
          if @user = Authentication.find_by_user_id(current_user.id)
            @user.update(password_reset_params)
             UserMailer.password_reset_success(@user).deliver_now
               format.html { redirect_to signin_url,:flash => {:success => 'password successfully Reseted login now.' }}
               format.json { }
         else
           format.html { redirect_to forget_password_accounts_path, :flash => {:danger => 'Something went wrong please try again.' }}
           format.json { }
         end
       end
      else
        format.html { redirect_to forget_password_accounts_path, :flash => {:danger =>'Password Missmatch..' } }
        format.json { }
      end
    end
  end

  def signout
    sign_out
    redirect_to root_path
  end

  def check_email
    @profile = Authentication.find_by_email(params[:email])
    if !@profile
      render text: 'new'
    else
      render text: '<div class="alert alert-danger text-center" role="alert">Email is Already Registered With US!</div>'.html_safe
    end
  end

  def email_check
    @profile = Authentication.find_by_email(params[:email])
    if @profile
      render text: 'new'
    else
      render text: '<div class="alert alert-danger text-center" role="alert">Email is Not Registered With US!</div>'.html_safe
    end
  end

  def logo
    logo = Default.find_by_id(1)
    send_data(logo.logo,:type => "image/png",:disposition => "inline")
  end

  def icon
    icon = Default.find_by_id(1)
    send_data(icon.icon,:type => "image/png",:disposition => "inline")
  end

  def default_dp
    logo = Default.find_by_id(1)
    send_data(logo.default_db,:type => "image/png",:disposition => "inline")
  end



  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def authen_params
      params.require(:profile).permit(:forgetkey,:email)
    end

    def authsignup_params
      params.require(:user).permit(:email,:password,:user_id)
    end

    def password_reset_params
      params.require(:profile).permit(:password)
    end

    def check_key
    if params[:f_key].present?
      @user = Authentication.find_by_forgetkey(params[:f_key])
      if !@user.present?
        flash[:danger] = 'Somethig went wrong try again'
        redirect_to forget_password_accounts_path
      end
    else
      signed_in_user
    end

  end

end

app/helpers/accounts_helper.rb
module AccountsHelper

  def logo
    id =1
    default = Default.find_by_id(1)
    if default.present?
       url_for( :action => "logo",:id => id, :controller=> "accounts" )
    end
  end

  def icon
    id =1
    default = Default.find_by_id(1)
    if default.present?
       url_for( :action => "icon",:id => id, :controller=> "accounts" )
    end
  end
  
end

app/views/accounts/_form.html.erb
<%= form_for(user,role:"form",:multipart => 'true') do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row justify-content-md-center mt-3 ">
    <div class="col-5 all_border">
          <div class="form-group ">
              <%= f.label :name,class: "control-label" %>
              <%= f.text_field :name,class: "form-control",placeholder: "Name:",:required => true  %>
          </div>

          <div class="form-group">
              <%= f.label :email,class: "control-label" %>
              <%= f.email_field :email,class: "form-control",placeholder: "Email:",:required => true ,id: "check_email" %>
          </div>
          <div class="form-group">
              <%= f.label :password,class: "control-label" %>
              <%= f.password_field :password,class: "form-control",placeholder: "password", :required =>true %>
          </div>
          <div class="form-group">
              <%= f.label :phone,class: "control-label" %>
              <%= f.text_field :phone,class: "form-control",placeholder: "Phone",:required =>true, pattern: "\\d*" %>
          </div>

          <div class="form-group">
              <%= f.label :Photo,class: "control-label" %>
              <%= f.file_field :image,class: "form-control-file btn btn-default" %>
          </div>

        <div class="form-group">
          <label for="gender_choose" class="control-label"> Gender : &nbsp;</label>
          <select name="user[gender]" class="custom-select" id="gender_choose">
            <option selected> Choose..</option>
            <option value="King">King</option>
            <option value="Queen">Queen </option>
          </select>
        </div>

        <div class="form-group">
          <%= f.label :city,class: "control-label" %>
          <%= f.text_field :city,class: "form-control",placeholder: "City",:required => true %>
        </div>

        <div class="form-group">
          <%= f.label :country,class: "control-label" %>
          <%= f.text_field :country,class: "form-control",placeholder: "Country",:required=>true %>
        </div>

        <div class="form-group">
            <%= f.label :Few_lines_about_me,class: "control-label" %>
            <%= f.text_area :aboutme,class: "form-control",placeholder: "About me",:required=>true %>
        </div>

        <div class="row">
          <p class="text-right"><%= link_to "Already Member Signin !!!!",signin_path %> </p>
        </div>

        <div class="row">
          <%= f.submit "Sign up ",class: "btn btn-outline-primary col-md-3 offset-md-5", id:"signup_form"%>
        </div>

      </div>
  </div>
<% end %>

app/views/accounts/forget_password.html.erb
<% flash.each do |key,msg| %>
 <div class="text-center alert alert-<%= key %>"><%= msg %></div>
<% end %>
<div id="password_reset_msg"></div>
<h2 class="text-center mt-5"> <img src=" <%= icon %>" height="50" width="50" class="img-fluid"> Singersarena </h2>

<div class="row justify-content-md-center">
    <%= form_for(:profile, url: forget_password_accounts_path,:remote => true, method: :GET,:html => {id: "forget_password"}) do |f|  %>
      <div class="row">
        <div class="col-12 mt-3 all_border">
          <div class="row">
            <%= f.label :Email %>
            <%= f.email_field :email,class:"form-control",placeholder: "Email", id: "email_check" %>
          </div>
          <div class="row justify-content-md-center">
            <%= f.submit "Reset", class: "btn btn-outline-primary text-center mt-2", id: "signin_form" %>
          </div>
    </div>
      </div>
      <% end %>
    </div>

app/views/accounts/new.html.erb
<% flash.each do |key,msg| %>
 <div class="text-center alert alert-<%= key %>"><%= msg %></div>
<% end %>
<div id="sign_up_error"></div>
<div class="container">
      <h2 class="text-center justify-content-md-center mt-5"><img src="<%= icon %>" height="50" width="50" class="img-fluid" >&nbsp;Singersarena</h2>
      <%= render 'form', user: @user %>
</div>

app/views/accounts/password_reset.html.erb
<% flash.each do |key,msg| %>
 <div class="text-center alert alert-<%= key %>"><%= msg %></div>
<% end %>

  <h2 class="text-center mt-5"> <img src="<%= icon %>" height="50" width="50" class="img-fluid"> Singersarena </h2>

<div class="row justify-content-md-center mt-3">
    <%= form_for(:profile, url: password_change_accounts_path, remote: true,  id: "password_reset") do |f|  %>
      <div class="row">
        <div class="col-12 all_border">
          <div class="row">
            <%= f.label :Password %>
            <%= f.password_field :password,class:"form-control",placeholder: "**********", id: "password" %>
          </div>
          <div class="row">
            <%= f.label :Retype_Password %>
            <%= f.password_field :again_password,class:"form-control",placeholder: "**********", id: "password_again" %>
          </div>
          <div class="row">
            <%= f.hidden_field :f_key,value: params[:f_key] %>
          </div>

          <div class="row justify-content-md-center">
            <%= f.submit "Reset", class: "btn btn-default text-center mt-2", id: "reset_form" %>
          </div>
        </div>
      </div>
      <% end %>
    </div>

app/views/accounts/signin.html.erb
<% flash.each do |key,msg| %>
 <div class="text-center alert alert-<%= key %>"><%= msg %></div>
<% end %>


<h2 class="text-center mt-5"> <img src="<%= icon %>" height="50" width="50" class="img-fluid"> Singersarena </h2>

<div class="row justify-content-md-center">
 <%= form_for(:login, url: login_path) do |f| %>
 <div class="row">
   <div class="col-12 mt-3 all_border">
     <div class="row">
       <%= f.label :email %>
       <%= f.email_field :email,class: "form-control",placeholder: "Email", id: "email_check", required: true %>
     </div><p></p>
     <div class="row">
       <%= f.label :Password%>
       <%= f.password_field :password,class: "form-control",placeholder: "Password", 'aria-describedby' => "passHelp", required: true  %>
       <small id="passhelp" class="form-text text-muted"><%= link_to "Forgot Password?",forget_password_accounts_path %> </small>
     </div><p></p>
     <div class="row">
       <p class="text-right"><%= link_to "Don't have acccount Signup !!!!",signup_path %></p>
     </div>
     <div class="row justify-content-md-center">
       <%= f.submit "Signin",class: "btn btn-default btn-outline-primary  text-center", id: "signin_form" %>
     </div>
   </div>
 </div>
<% end %>
</div>